### ISSUE TITLE
Repository not synced with Bitkeeper

### ISSUE THREAD

**Issue by glaubitz** [ntp-project/ntp#1]
I would like to make a contribution to the ntp project, but noticed that the github repository hasn't been updated for three years.

I have not worked with Bitkeeper before as Bitkeeper has traditionally been a commercial software and git has been the tool of choice for years now for most developers.

Would it be possible to keep the git repository in sync with Bitkeeper or even switch to git on github completely?

**Comment by sshock** [comment]
I'm also really confused because according to [this page](https://support.ntp.org/bin/view/Main/SoftwareDevelopment#NTP_Source_Code_Repositories) the github and bitkeeper repos are "fully and automatically synchronized".

Also, I emailed webmaster@ntp.org to ask about it and it bounced with an "Address not found" reply.

**Comment by sshock** [comment]
I also found this: https://bugs.ntp.org/show_bug.cgi?id=3413

**Comment by sshock** [comment]
I posted a complaint on the [comp.protocols.time.ntp group](https://groups.google.com/g/comp.protocols.time.ntp/c/JwcfZy7LMgE), but I don't know if anyone will actually see it.

**Comment by hartwork** [comment]
In it's current state, this repository is near useless. Could it be synced or marked as archived please? If would save people time looking in the wrong place. Thanks :pray:

**Comment by JamesB192** [comment]
Checkout the ntp-stable and ntp-devel branches of https://github.com/jamesb192/ntp.git, which are currently up to 4.2.8P17 and 4.3.102, respectively. Maybe someone upstream can fix the sync with this repository.

Edit: Fixed ntp-devel branch name.

**Comment by sjvudp** [comment]
Maybe the top README should be updated, specifically explaining the relationship of this repository (and the issues reported) to the ntp.org website and bugzilla. I mean: It's not clear what the primary site/repository is,

**Comment by sjvudp** [comment]
> Checkout the ntp-stable and ntp-devel branches of https://github.com/jamesb192/ntp.git, which are currently up to 4.2.8P17 and 4.3.102, respectively. Maybe someone upstream can fix the sync with this repository.
> 

But having "yet another fork" of the NTP repository isn't actually helpful: Now you have three instead of two. Which is the official one to contribute to?

**Comment by JamesB192** [comment]
>
> But having "yet another fork" of the NTP repository isn't actually
> helpful: Now you have three instead of two. Which is the official one to
> contribute to?
>
>
Not this repository; not any of my three copies; not any copy of ntpsec; in
fact not any copy you can get via tarball, zip, or git.

The only "official" repositories worth their name are Bitkeeper and
probably hidden. After that would be bk.ntp.org, my three copies, NTPsec at
git-conversion~1, and then this old thing.

Are you confused yet? My default would be to throw patches onto an
appropriate mailing list and hope someone picks it up.

**Comment by dlavigne-nwtime** [comment]
The bk to git sync automation has been fixed and a template has been added to send the reporter to the right place when creating a new issue.
