### ISSUE TITLE
why ntp client authenticate server using autokey protocol wthout server key  that is ok?

### ISSUE THREAD

**Issue by haitang002** [ntp-project/ntp#11]
Configuration method reference：
http://support.ntp.org/bin/view/Support/ConfiguringAutokey

**Comment by hstenn** [comment]
Autokey has been documented as being unsafe since sometime around 2012.

Even though it is unsafe, it should still behave as documented.

Exactly what steps did you follow that demonstrate the problem you describe?

**Comment by dlavigne-nwtime** [comment]
Closing for lack of feedback. If this is still an issue, please create a report at bugs.ntp.org containing the details.
