### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by 4erepaxen** [ntp-project/ntp#17]
While looking at the licenses of the files, I noticed that the file is licensed GPLv3+.
(/sntp/libopts/m4/libopts.m4)
Therefore, when building with static linking, this license is transferred to the entire package, as far as I understand.
Looking through the library versions for the same file, I didn't find this license.
If you have the opportunity, could you add an exception.(https://spdx.org/licenses/Autoconf-Exception-macro.html)
or explicitly indicate this nuance.

**Comment by hart-NTP** [comment]
see sntp/libopts/README:

       THIS TARBALL IS NOT A FULL DISTRIBUTION.

The contents of this tarball is designed to be incorporated into
software packages that utilize the AutoOpts option automation package
and are intended to be installed on systems that may not have libopts
installed.  It is redistributable under the terms of either the LGPL
(see COPYING.lgpl) **or under the terms of the advertising clause free BSD
license (see COPYING.mbsd)**.

Usage Instructions for autoconf/automake/libtoolized projects:

1. Install the unrolled tarball into your package source tree,
   copying ``libopts.m4'' to your autoconf macro directory.
[...]

If you still think the mention of GPLv3 in libopts.m4 is a problem, I think the best place to address that is with its author Bruce Korb directly.

**Comment by 4erepaxen** [comment]
In any case, I appreciate the quick response to my question.

**Comment by 4erepaxen** [comment]
I re-read the license and the reference you gave.
I think you're right, and this can be considered part of section seven of the GPLv3 license.(Additional Terms)
