### ISSUE TITLE
The time of ntp client was added 2^32 seconds by ntp server when we deployed cluster, unexpectedly.

### ISSUE THREAD

**Issue by h3c-open** [ntp-project/ntp#2]
We know that max seconds of transmiting message updating time among different clients by the ntp are 2^32 seconds, but time difference are only 2 years between server and clinet actually. So I do not know how is it ? Can someone give me some suggestions, thank you in advance！

**Comment by hstenn** [comment]
more information would be helpful.
What version of ntpd are you running?
ntpd has its build date compiled in, so it knows "now" time cannot be earlier than this date.

Behavior like you describe has only been observed when a human decides to try crazy dates.

**Comment by sjvudp** [comment]
> We know that max seconds of transmiting message updating time among different clients by the ntp are 2^32 seconds, but time difference are only 2 years between server and clinet actually. So I do not know how is it ? Can someone give me some suggestions, thank you in advance！

With the information given it's hard to decide what happened actually, not to talk about whether it's a bug or not.

**Comment by dlavigne-nwtime** [comment]
Closing for lack of feedback. If this is still an issue, please open a bug report with details at https://bugs.ntp.org.
