### ISSUE TITLE
Why do you have to wait 5 minutes for the local clock ntpd to be accessible by the clients？

### ISSUE THREAD

**Issue by HorsonLiu** [ntp-project/ntp#5]
Why do you have to wait 5 minutes for the local clock ntpd to be accessible by the clients？

**Comment by hstenn** [comment]
Please describe your NTP environment and the ntp.conf file for your master servers.  If you don't want to publish that information please let us know how to contact you.

**Comment by HorsonLiu** [comment]
My question comes from FAQ in http://www.ntp.org/ntpfaq/NTP-s-trbl-general.htm#AEN5235:
> 8.2.3.2. My server is up and running, but it is unusable for clients
> Well, this is the answer for the impatient: Probably you have made no mistakes, but you simply have to wait for about **five minutes** until the server synchronizes to a time reference for the first time. If you changed the minpoll parameter, the wait time may change accordingly.

In fact, I found that if I comment out the ‘driftfile’ in the configuration file, I would have to wait five minutes for ntpd to serve properly.

**Comment by hstenn** [comment]
That is old information and we are working to update it.  It is better to use iburst to get a machine synchronized faster.
