### ISSUE TITLE
Build instructions unclear -- is this repo maintained?

### ISSUE THREAD

**Issue by jchia** [ntp-project/ntp#6]
The project may be assuming some old project building convention related to autotools that not everyone is familiar with especially people who are more familiar with other build tools, or maybe the documentation is just out-of-date.

Particularly, INSTALL refers to a file called 'configure' which does not exist. INSTALL also talks about running autoconf to generate configure from configure.in, but configure.in doesn't exist, either. There is configure.ac but there is no mention of it.

The biggest problem is that configure is missing. Normally, people run configure followed by make. Maybe there is some unspoken rules about how to generate configure from some other files that people familiar with autotools would know, but this is not generally clear to me. Since the last commit is 2016, maybe this repo is unmaintained?

**Comment by egberts** [comment]
Normally for end-user to be able to do a quick configure make, make test, then make install, the following file is needed as a minimum:

* configure.in

If I see the configure.ac, then I run my script to do the autotool rebuilding (which is the maintainer's job to do instead):

```
#!/bin/bash

echo "DDDD   EEEEE  BBBB   U   U   GGG"
echo "D   D  E      B   B  U   U  G"
echo "D   D  EEEE   BBBB   U   U  G GGG"
echo "D   D  E      B   B  U   U  G   G"
echo "DDDD   EEEEE  BBBB    UUU    GGG"

VERBOSE="--verbose"
PREFIX=${PREFIX:-/usr/local}
if [ ! -d "$PREFIX" ]; then
  echo "$PREFIX is not a directory; aborting"
  exit 1
fi
echo "PREFIX is going to $PREFIX dirspec."


rm -rf autom4te.cache

echo libtoolize ${VERBOSE} --copy --force
libtoolize ${VERBOSE} -i --copy --force
RETSTS=$?
if [ $RETSTS -ne 0 ]; then
  echo "libtoolize failed: $RETSTS"; exit $RETSTS
fi

if [ -d m4 ]; then
  echo "aclocal $VERBOSE -I m4 -Wall ${ACLOCAL_ARGS}"
  aclocal $VERBOSE -I m4 -Wall ${ACLOCAL_ARGS}
  # serial-tests available since automake v1.1.11
  echo "m4_define([UV_EXTRA_AUTOMAKE_FLAGS], [$UV_EXTRA_AUTOMAKE_FLAGS])" \
       > m4/libuv-extra-automake-flags.m4
else
  echo "aclocal -Wall $VERBOSE ${ACLOCAL_ARGS}"
  aclocal $VERBOSE -Wall ${ACLOCAL_ARGS}
fi
RETSTS=$?
if [ $RETSTS -ne 0 ]; then
  echo "aclocal failed: $RETSTS"; exit $RETSTS
fi

echo autoheader -Wall ${VERBOSE}
autoheader -Wall ${VERBOSE}
RETSTS=$?
if [ $RETSTS -ne 0 ]; then
  echo "autoheader failed: $RETSTS"; exit $RETSTS
fi

echo autoconf -Wall ${VERBOSE}
autoconf -Wall ${VERBOSE}
# autoconf --warning=all ${VERBOSE} --trace=MACRO_NAME
RETSTS=$?
if [ $RETSTS -ne 0 ]; then
  echo "autoconf failed: $RETSTS"; exit $RETSTS
  exit $RETSTS
fi

if [ -f Makefile.am ]; then
  AUTOMAKE_OPTIONS="--add-missing --force-missing --foreign --copy --warnings=ov
erride -Wall"
  echo "automake ${VERBOSE} ${AUTOMAKE_OPTIONS}"
  automake ${VERBOSE} ${AUTOMAKE_OPTIONS}
  RETSTS=$?
  if [ $RETSTS -ne 0 ]; then
    echo "automake failed: $RETSTS"; exit $RETSTS
  fi
else
  echo "Makefile.am not found; SKIPPING AUTOMAKE..."
  exit $RETSTS
fi

echo "./configure --enable-debug --prefix=/usr $1 $2 $3 $4 $5"
./configure --enable-debug --prefix=/usr $1 $2 $3 $4 $5
RETSTS=$?
if [ $RETSTS -ne 0 ]; then
  echo "configure failed: $RETSTS"; exit $RETSTS
  exit $RETSTS
fi

NUMCPUS="$(getconf _NPROCESSORS_ONLN)"
echo "Now execute 'make -j$NUMCPUS'"
echo "make -j$NUMCPUS"
make -j$NUMCPUS
RETSTS=$?
if [ $RETSTS -ne 0 ]; then
  echo "make failed: $RETSTS"; exit $RETSTS
fi

echo "Status: $RETSTS"
```

Do my `make test`, then `make install`

**Comment by hartwork** [comment]
The repository is out of date (see #1) so building this code is probably a waste of time, but for anyone who still likes to try, here's what I would do:

```console
cd "$(mktemp -d)"
git clone --depth 1 https://github.com/ntp-project/ntp
cd ntp/
./bootstrap 
./configure && make -j2
```

Note that you will need to have lynx installed.

**Comment by hstenn** [comment]
The usual way folks build and install the software is from a tarball.

The documentation says this, and also provides instructions on how to build from a repo. @hartwork pretty much describes the process.

This git repo has not been updated in a while.

The documentation also talks about which repos are supported/active.

This repo should become regularly updated, soonish.

**Comment by hartwork** [comment]
@hstenn building software just from tarballs does not work for people that want to contribute; they need a way to build right from Git.

**Comment by hart-NTP** [comment]
We use Bitkeeper (www.bitkeeper.org) in the same role you're accustomed to using git.  You can clone from bk://bk.ntp.org/ntp-dev and bk://bk.ntp.org/ntp-stable.

If you're using Linux, you may have to build Bitkeeper from source code.  The Windows, macos, and FreeBSD binaries on bitkeeper.org work well on current versions of those OSes.

**Comment by hstenn** [comment]
@hartwork for contributors, the build and code contribution process is (poorly) documented at...
* https://support.ntp.org/Main/WebHome#Building_NTP, which mentions
* https://support.ntp.org/Main/SoftwareDevelopment

with more info at https://support.ntp.org/Dev/WebHome

Pretty much all of the content would benefit from some TLC.
